server {
    listen 80;
    server_name YOUR_DOMAIN_OR_VPS_IP;

    client_max_body_size 10M;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        alias /home/perfumeapp/perfume_labels_system/staticfiles/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/perfumeapp/perfume_labels_system/gunicorn.sock;
    }
}
