# Generated by Django 6.1 on 2026-09-02 08:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='perfume name')),
                ('ingredients_text', models.TextField(blank=True, verbose_name='ingredients')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, verbose_name='EZLOT batch number')),
                ('is_active', models.BooleanField(default=True, verbose_name='active batch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='labels.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'batch',
                'verbose_name_plural': 'batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='print date')),
                ('serial', models.CharField(max_length=20, unique=True, verbose_name='serial')),
                ('tracking_number', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='tracking number')),
                ('reprint_count', models.PositiveIntegerField(default=0, verbose_name='times reprinted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_labels', to='labels.batch', verbose_name='batch')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='printed by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_labels', to='labels.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'tracking label',
                'verbose_name_plural': 'tracking labels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('product', 'batch_number'), name='unique_batch_per_product'),
        ),
    ]
