# Generated by Django 6.1 on 2026-09-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinglabel',
            name='serial',
            field=models.CharField(max_length=20, verbose_name='serial'),
        ),
    ]
