# Generated by Django 5.2.17 on 2026-09-06 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_trackinglabel_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinglabel',
            name='batch_number_snapshot',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='EZLOT batch (snapshot)'),
        ),
        migrations.AddField(
            model_name='trackinglabel',
            name='product_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='perfume name (snapshot)'),
        ),
        migrations.AlterField(
            model_name='trackinglabel',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_labels', to='labels.batch', verbose_name='batch'),
        ),
        migrations.AlterField(
            model_name='trackinglabel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_labels', to='labels.product', verbose_name='product'),
        ),
    ]
