# Generated by Django 5.2.17 on 2026-09-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_trackinglabel_batch_number_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tracking_preview',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='tracking number preview'),
        ),
    ]
