# Generated by Django 5.2.17 on 2026-09-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_product_tracking_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(max_length=50, verbose_name='batch number'),
        ),
        migrations.AlterField(
            model_name='trackinglabel',
            name='batch_number_snapshot',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='batch number (snapshot)'),
        ),
    ]
