# Generated by Django 5.2.17 on 2026-09-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0005_alter_batch_batch_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tracking_preview',
        ),
        migrations.AddField(
            model_name='product',
            name='oil_batch_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='oil batch number'),
        ),
    ]
