# Generated by Django 5.2.17 on 2026-09-09 13:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0006_remove_product_tracking_preview_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinglabel',
            name='print_time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='print time'),
        ),
        migrations.CreateModel(
            name='IngredientLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(blank=True, default='', max_length=200, verbose_name='perfume name (snapshot)')),
                ('oil_batch_snapshot', models.CharField(blank=True, default='', max_length=50, verbose_name='oil batch snapshot')),
                ('print_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='print date')),
                ('print_time', models.TimeField(auto_now_add=True, null=True, verbose_name='print time')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity printed')),
                ('note', models.TextField(blank=True, default='', verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='printed by')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_labels', to='labels.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'ingredient label',
                'verbose_name_plural': 'ingredient labels',
                'ordering': ['-created_at'],
            },
        ),
    ]
